fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.0.2
  symlinks:
    iptables: "#{source_dir}"
