fixtures:
  repositories:
    stdlib:
      repo: https://github.com/puppetlabs/puppetlabs-stdlib
      ref: 4.6.0
    firewall:
      repo: https://github.com/puppetlabs/puppetlabs-firewall
      ref: 1.6.0
    augeasproviders_core:
      repo: https://github.com/hercules-team/augeasproviders_core
    augeasproviders_sysctl:
      repo: https://github.com/hercules-team/augeasproviders_sysctl
  symlinks:
    iptables: "#{source_dir}"
