fixtures:
  repositories:
    stdlib:
      repo: git://github.com/puppetlabs/puppetlabs-stdlib.git
      ref: 4.2.0
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.1.1
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: v1.2.0
  symlinks:
    iptables: "#{source_dir}"
