fixtures:
  repositories:
    stdlib: git://github.com/puppetlabs/puppetlabs-stdlib.git
    firewall:
      repo: git://github.com/puppetlabs/puppetlabs-firewall.git
      ref: 1.1.1
    augeasproviders:
      repo: git://github.com/hercules-team/augeasproviders.git
      ref: v1.1.0
  symlinks:
    iptables: "#{source_dir}"
