name 'treydock-iptables'
version '1.1.0'
author 'treydock'
license 'Apache License, Version 2.0'
project_page 'UNKNOWN'
source 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
dependency 'puppetlabs/stdlib', '>=3.2.0'
dependency 'puppetlabs/firewall', '>=0.4.0'
