name 'treydock-iptables'
version '2.0.0'
author 'treydock'
license 'Apache License, Version 2.0'
project_page 'UNKNOWN'
source 'UNKNOWN'
summary 'UNKNOWN'
description 'UNKNOWN'
dependency 'puppetlabs/stdlib', '>=3.2.0 <5.0.0'
dependency 'puppetlabs/firewall', '1.x'
dependency 'domcleal/augeasproviders', '1.x'
